name: Build
on:
  workflow_call:
    inputs:
      upload-artifact:
        type: boolean
        default: true
      tag-name:
        type: string
        default: "draft"
      channel:
        type: string
        default: "dev"

env:
  IS_GITHUB_ACTIONS: 1
  CHANNEL: "${{ inputs.channel }}"
  FLUTTER_VERSION: '3.38.5'
  NDK_VERSION: r28c
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.tag-name }}"
  TARGET_NAME_ipa: "Hiddify-iOS"

jobs:
  test:
    outputs:
      draftBuildCode: ${{ steps.draftBuildCode.outputs.datetime }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
          
      - name: Prepare
        run: make linux-amd64-prepare
      - name: Test
        run: flutter test

      - name: make draftBuildCode
        id: draftBuildCode
        run: echo "::set-output name=datetime::$(date +'%d.%H.%M')"

  build:
    needs: test
    permissions: write-all
    continue-on-error: true

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ios
            os: macos-15
            aarch: universal
            filename: hiddify-ios
            targets: ipa
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.21.0
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
                  
      - name: Setup dependencies
        run: |
          make ${{ matrix.platform }}-install-deps  
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Prepare for ${{ matrix.platform }}
        run: |
          make ${{ matrix.platform }}-prepare

      - name: Disable iOS Code Signing
        if: matrix.platform == 'ios'
        run: |
          sed -i '' 's/CODE_SIGNING_ALLOWED = YES/CODE_SIGNING_ALLOWED = NO/g' ios/Runner.xcodeproj/project.pbxproj || echo "No explicit flags"
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/Runner.xcodeproj/project.pbxproj || echo "No style flags"

      - name: Build ${{ matrix.platform }}
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          flutter build ipa --no-codesign --target lib/main.dart --dart-define sentry_dsn="" --dart-define FLUTTER_BUILD_NAME=4.1.2 --dart-define FLUTTER_BUILD_NUMBER=40102
          mkdir -p dist/ios/Payload
          cp -r build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app dist/ios/Payload/
          cd dist/ios && zip -r Hiddify-iOS.ipa Payload && rm -rf Payload && cd ../..

      - name: Copy to out unix
        if: matrix.platform == 'ios'
        run: |
          ls -R dist/
          mkdir out
          mkdir tmp_out
          
          for EXT in $(echo ${{ matrix.targets }} | tr ',' '\n'); do
            KEY=TARGET_NAME_${EXT}
            FILENAME=${!KEY}
            echo "For $EXT ($KEY) filename is ${FILENAME}"
            mv dist/*/*.$EXT tmp_out/${FILENAME}.$EXT
            ls tmp_out
            if [[ "${{matrix.platform}}" == 'ios' ]];then
              echo mv tmp_out/${FILENAME}.$EXT out/
              mv tmp_out/${FILENAME}.$EXT out/
            fi
          done

      - name: Upload Artifact
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v6
        with:
          name: ${{matrix.platform}}
          path: ./out
          retention-days: 1

      - name: Clean up keychain and provisioning profile
        if: ${{ always() && startsWith(matrix.os,'macos')}}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db ||echo ok
          rm ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision ||echo ok

  update-draft:
    permissions: write-all
    if: ${{ inputs.upload-artifact }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/
          
      - name: Display Files Structure
        run: ls -R
        working-directory: ./out

      - name: Delete Current Release Assets
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'draft'
          deleteOnlyFromDrafts: false
          
      - name: prepare_release_message
        continue-on-error: true
        run: |
          set +e 
          sed 's|RELEASE_TAG|${{ env.TAG_NAME }}|g' ./.github/release_message.md > release.md
          pip install gitchangelog pystache mustache markdown
          prelease=$(curl --silent "https://api.github.com/repos/hiddify/hiddify-app/releases/latest" | grep -Po '"tag_name": "\K([^"]*)') 
          echo -e "\n\n<details markdown=1><summary>All changes from $current to the latest commit:</summary>\n\n">>release.md
          gitchangelog "${prelease}.." >> release.md  2>&1 || echo "Error in gitchangelog"
          echo -e "\n\n</details>">>release.md

      - name: Create or Update Draft Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./out/*
          name: 'draft'
          tag_name: 'draft'
          body_path: './release.md'
          prerelease: true

      - name: Create or Update Draft Release (Hiddify Repository)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_HIDDIFY_APP_REPO }}
          GITHUB_REPOSITORY: hiddify/hiddify-app
        with:
          files: ./out/*
          name: 'draft'
          tag_name: 'draft'
          body_path: './release.md'
          target_commitish: '530bf77839a74d4f13847ba244a20734ac7ab119'
          prerelease: true
          repository: hiddify/hiddify-app

  upload-release:
    permissions: write-all
    if: ${{ inputs.upload-artifact && inputs.tag-name != 'draft' }}
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: Download Artifact
        uses: actions/download-artifact@v7
        with:
          merge-multiple: true
          pattern: "*"
          path: ./out/

      - name: Display Files Structure
        run: |
          ls -R ./out
          ls -R ./.github/
          ls -R ./.git/

      - name: prepare_release_message
        run: |
          sed 's|RELEASE_TAG|${{ env.TAG_NAME }}|g' ./.github/release_message.md >> release.md

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}
          body_path: './release.md'
          files: ./out/*
